### ISSUE TITLE
Models review

### ISSUE THREAD

**Issue by wzs1234566** [Book4U-ECSE428/backend#1]
# review model entities and their relationships
# Everyone should sign off on this 
https://github.com/Book4U-ECSE428/backend/blob/93cca9fa26d23b8f9dbb19afed8b1bdd9634ee6f/code/books4u/models.py#L1-L114

**Comment by xiaozhou-liao** [comment]
- There should be another tuple ("Moderator", 'Moderator') in PERMISSION_CHOICES
- For Book class, it might be better to make the on_delete relation to category and author to be SET_NULL or Protected, since CASCADE is too destructive, i.e. delete a category will lead to the deletion of all books under that category.
- For Review class, I think the relation from Review to Book should be "book = ForeignKey(Book, on_delete=models.CASCADE)" instead of one to one. And we don't need BigInteger for rating, instead we can have "rating = models.IntegerField(validators=[MaxValueValidator(5), MinValueValidator(1)])"
- For Vote class, similar to review-book, for Vote-Review, I thinks we should have "review= ForeignKey(Review, on_delete=models.CASCADE)" instead of one to one. In fact, we don't need Vote to be a class, why not make it an integer field in Review just showing how many times has it been voted.

**Comment by xiaozhou-liao** [comment]
For content field of Review, I remember that in our requirement, a review can not exceed 400 characters, but we currently have "content = models.CharField(max_length=9999) "
For gender field of User, I suggest to make the default ""

**Comment by wzs1234566** [comment]
@xiaozhou-liao 
1. moderators are just regular users with permission("normal"), if needed lated we can add more permissions.
2. good catch
3. user - review - book, one user has many reviews, each review only has one book. 
4. user - vote - review, same relationship with above. 3,4 need not change.
5. for the length of content, I think 400 chars is too short for an book review, and each Chinese char may take more than one "char". This needs to be decided by our PM @billchizhang

**Comment by wzs1234566** [comment]
I created a PR for reviewing models, this issue will be closes. please address any issue in PR https://github.com/Book4U-ECSE428/backend/pull/2
